name: workflow practice
on: push
jobs:
  lint:
    runs-on: ubuntus-latest
    steps:
      - name: get code 
        uses: actions/checkout@v3
      - name: install dependencies
        run: npm ci
      - name: run code
        run: npm lint
  test:
    needs: lint
    runs-on: ubuntus-latest
    steps:
      - name: get code 
        uses: actions/checkout@v3
      - name: install dependencies
        run: npm ci
      - name: run code
        run: npm test
  build:
    needs: test
    runs-on: ubuntus-latest
    steps:
      - name: get code 
        uses: actions/checkout@v3
      - name: install dependencies
        run: npm ci
      - name: run code
        run: npm build
   
